DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE INV CASCADE CONSTRAINTS;
DROP TABLE ORDER_ENTER CASCADE CONSTRAINTS;
DROP TABLE SALE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_ATT_NO;
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_EVNT_NO;
DROP SEQUENCE SEQ_PRO_NO;
DROP SEQUENCE SEQ_INV_NO;
DROP SEQUENCE SEQ_OE_NO;
DROP SEQUENCE SEQ_SALE_NO;


CREATE SEQUENCE SEQ_ATT_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE SEQ_EVNT_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE SEQ_PRO_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE SEQ_INV_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE SEQ_OE_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE SEQ_SALE_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE TABLE ATTACHMENT (
    ATT_NO NUMBER CONSTRAINT PK_ATT PRIMARY KEY,
    ATT_NAME VARCHAR2(300) NOT NULL
);

CREATE TABLE MEMBER (
    USER_NO NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_RNO VARCHAR2(150) NOT NULL UNIQUE,
    USER_NAME VARCHAR2(150) NOT NULL,
    USER_EMAIL VARCHAR2(150) NOT NULL,
    USER_PHONE VARCHAR2(30) NOT NULL,
    USER_BRANCH VARCHAR2(150) NOT NULL,
    USER_OPENDATE DATE NOT NULL,
    USER_ATT_NO NUMBER NULL CONSTRAINT FK_MEMBER_ATT REFERENCES ATTACHMENT
);

CREATE TABLE EVENT (
    EVNT_NO NUMBER CONSTRAINT PK_EVENT PRIMARY KEY,
    EVNT_TITLE VARCHAR2(150) NOT NULL,
    EVNT_CONTENT VARCHAR2(900) NOT NULL,
    EVNT_DATE_S DATE NOT NULL,
    EVNT_DATE_E DATE NOT NULL,
    EVNT_ATT_NO NUMBER NULL CONSTRAINT FK_EVENT_ATT REFERENCES ATTACHMENT
);

CREATE TABLE CATEGORY (
    CAT_NO NUMBER CONSTRAINT PK_CATEGORY PRIMARY KEY,
    CAT_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCT (
    PRO_NO NUMBER CONSTRAINT PK_PRO PRIMARY KEY,
    PRO_NAME VARCHAR(300) NOT NULL UNIQUE,
    PRO_PRICE_S NUMBER NOT NULL,
    PRO_PRICE_E NUMBER NOT NULL,
    PRO_CAT_NO NUMBER NOT NULL CONSTRAINT FK_PRODUCT_CAT REFERENCES CATEGORY
);

CREATE TABLE INV (
    INV_NO NUMBER CONSTRAINT PK_INV PRIMARY KEY,
    INV_NAME VARCHAR2(300) NOT NULL CONSTRAINT FK_INV_NAME REFERENCES PRODUCT(PRO_NAME),
    INV_W_COUNT NUMBER NOT NULL,
    INV_S_COUNT NUMBER NOT NULL,
    INV_PRICE NUMBER NOT NULL,
    INV_CAT_NO NUMBER NOT NULL CONSTRAINT FK_INV_CAT REFERENCES CATEGORY,
    USER_NO NUMBER NOT NULL CONSTRAINT FK_INV_MEMBER REFERENCES CATEGORY
);

CREATE TABLE ORDER_ENTER (
    OE_NO NUMBER,
    OE_COUNT NUMBER NOT NULL,
    OE_PRICE_E NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ENTER_DATE DATE NULL,
    OE_STATUS CHAR(1) NOT NULL CHECK(OE_STATUS IN ('Y', 'N')),
    OE_INV_NO NUMBER NOT NULL CONSTRAINT FK_ORDER_NO REFERENCES PRODUCT,
    OE_NAME VARCHAR2(300) NOT NULL CONSTRAINT FK_ORDER_NAME REFERENCES PRODUCT(PRO_NAME),
    OE_CAT_NO NUMBER NOT NULL CONSTRAINT FK_ORDER_CAT REFERENCES CATEGORY,
    USER_NO NUMBER NOT NULL CONSTRAINT FK_ORDER_MEMBER REFERENCES CATEGORY,
    CONSTRAINT PK_ORDER PRIMARY KEY(OE_NO, OE_INV_NO)	
    
);

CREATE TABLE SALE (
    SALE_NO NUMBER CONSTRAINT PK_SALE PRIMARY KEY,
    SALE_COUNT NUMBER NOT NULL,
    SALE_PRICE NUMBER NOT NULL,
    SALE_DATE DATE NOT NULL,
    SALE_CAT_NO NUMBER NOT NULL CONSTRAINT FK_SALE_CAT REFERENCES CATEGORY,
    SALE_NAME VARCHAR2(300) NOT NULL CONSTRAINT FK_SALE_NAME REFERENCES PRODUCT(PRO_NAME),
    USER_NO NUMBER NOT NULL CONSTRAINT FK_SALE_MEMBER REFERENCES CATEGORY
);


COMMIT;